#!/usr/bin/env python3
import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LOCAL_PROPERTIES = ROOT / "local.properties"


def print_step(message: str) -> None:
    print(f"\n[setup] {message}")


def find_executable(names):
    for name in names:
        path = shutil.which(name)
        if path:
            return path
    return None


def find_android_sdk_root():
    env_candidates = []
    for key in ("ANDROID_SDK_ROOT", "ANDROID_HOME"):
        value = os.getenv(key)
        if value:
            env_candidates.append(Path(value))

    candidates = []
    for item in env_candidates:
        candidates.append(item)

    if platform.system() == "Windows":
        home = os.getenv("LOCALAPPDATA")
        if home:
            candidates.append(Path(home) / "Android" / "Sdk")
        user_profile = os.getenv("USERPROFILE")
        if user_profile:
            candidates.append(Path(user_profile) / "AppData" / "Local" / "Android" / "Sdk")
        candidates.append(Path(r"C:\\Android\\Sdk"))
    elif platform.system() == "Darwin":
        candidates.append(Path.home() / "Library" / "Android" / "sdk")
        candidates.append(Path.home() / "Android" / "Sdk")
    else:
        candidates.append(Path.home() / "Android" / "Sdk")
        candidates.append(Path("/opt/android-sdk"))
        candidates.append(Path("/usr/lib/android-sdk"))

    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()
    return None


def detect_ndk_path(sdk_root: Path):
    if not sdk_root:
        return None
    ndk_candidates = [
        sdk_root / "ndk",
        sdk_root / "ndk-bundle",
    ]
    for base in ndk_candidates:
        if base.exists():
            for child in sorted(base.iterdir()):
                if child.is_dir() and (child / "source.properties").exists():
                    return child.resolve()
    return None


def ensure_local_properties(sdk_root: Path, ndk_root: Path):
    lines = ["# Auto-generated by setup.py", f"sdk.dir={sdk_root}", f"ndk.dir={ndk_root}"]
    LOCAL_PROPERTIES.write_text("\n".join(lines) + "\n", encoding="utf-8")


def install_java():
    if shutil.which("java") and shutil.which("javac"):
        return True

    print_step("Java was not found. Trying to install it with the available package manager...")
    if platform.system() == "Windows":
        if shutil.which("winget"):
            return subprocess.run(["winget", "install", "--id", "EclipseAdoptium.Temurin.17.JDK", "-e", "--source", "winget"], check=False).returncode == 0
        print("Install Java manually from https://adoptium.net/ or via your preferred package manager.")
        return False
    if platform.system() == "Darwin" and shutil.which("brew"):
        return subprocess.run(["brew", "install", "--cask", "temurin"], check=False).returncode == 0
    if shutil.which("apt"):
        return subprocess.run(["sudo", "apt-get", "update"], check=False).returncode == 0 and subprocess.run(["sudo", "apt-get", "install", "-y", "openjdk-17-jdk"], check=False).returncode == 0
    print("Install Java manually for your OS and re-run this script.")
    return False


def install_android_sdk_components(sdk_root: Path):
    if not sdk_root:
        print_step("Android SDK root was not found. Please install Android Studio or the command-line tools first.")
        return False

    sdkmanager = None
    for candidate in [
        sdk_root / "cmdline-tools" / "latest" / "bin" / "sdkmanager.bat",
        sdk_root / "cmdline-tools" / "latest" / "bin" / "sdkmanager",
        sdk_root / "bin" / "sdkmanager.bat",
        sdk_root / "bin" / "sdkmanager",
    ]:
        if candidate.exists():
            sdkmanager = candidate
            break

    if not sdkmanager:
        print_step("Android SDK command-line tools were not found. Install Android Studio or the command-line tools first.")
        return False

    print_step("Installing required Android SDK packages...")
    cmd = [str(sdkmanager), "--install", "platform-tools", "platforms;android-34", "build-tools;34.0.0"]
    if platform.system() == "Windows":
        cmd = [str(sdkmanager), "--install", "platform-tools", "platforms;android-34", "build-tools;34.0.0"]
    return subprocess.run(cmd, check=False).returncode == 0


def main():
    parser = argparse.ArgumentParser(description="Set up the Android project and local SDK paths")
    parser.add_argument("--skip-install", action="store_true", help="Only detect the SDK and write local.properties")
    args = parser.parse_args()

    print_step("Checking local development environment")

    java_ok = shutil.which("java") and shutil.which("javac")
    if not java_ok and not args.skip_install:
        install_java()
        java_ok = shutil.which("java") and shutil.which("javac")

    if not java_ok:
        print("Java is still missing. The Android build will not work until Java is installed.")
    else:
        print("Java detected.")

    sdk_root = find_android_sdk_root()
    if sdk_root:
        print(f"Android SDK detected at: {sdk_root}")
    else:
        print("Android SDK was not found. The script will still create a local.properties template.")

    ndk_root = detect_ndk_path(sdk_root) if sdk_root else None
    if ndk_root:
        print(f"Android NDK detected at: {ndk_root}")
    else:
        print("Android NDK was not found. The project may still build if the SDK installs it automatically.")

    if sdk_root is None:
        print_step("If Android Studio is installed, point the SDK to its SDK folder or set ANDROID_HOME/ANDROID_SDK_ROOT.")
    else:
        ensure_local_properties(sdk_root, ndk_root or sdk_root)
        print(f"Wrote {LOCAL_PROPERTIES}")

    if not args.skip_install and sdk_root:
        install_android_sdk_components(sdk_root)

    print("\nSetup complete. You can now run the build script to compile and install the app.")


if __name__ == "__main__":
    main()
